### ISSUE TITLE
Issue with `node-sass` version `4.0.0`

### ISSUE THREAD

**Issue by evilebottnawi** [niksy/node-sass-json-functions#5]
Output
```shell
Error: Cannot parse config file: '/path/to/my.js': Error: error in C function json-encode: value.getValue is not a function
```

**Comment by niksy** [comment]
Thanks for the reported issue! I’ve tried running tests against node-sass 4.0.0, but some tests fail which means this isn’t simple dependancy version change and will need to be looked further.

**Comment by niksy** [comment]
@evilebottnawi I’ve pushed fix for node-sass >= 4, can you confirm if this works for you?

**Comment by evilebottnawi** [comment]
@niksy yep
