### ISSUE TITLE
Why precision is always settled to 0?

### ISSUE THREAD

**Issue by 7iomka** [niksy/node-sass-json-functions#6]
https://github.com/niksy/node-sass-json-functions/blob/63d1da01e2d41aa162a294d9337c900c327b1732/lib/sass-to-json.js#L34
This cause unexpected issues
```
{
  value: sass.types.Number { dartValue: 0.1875rem },
  resolvedValue: '0rem'
}
```

**Comment by niksy** [comment]
Thanks for reporting this! I’ve added precision option which defaults to 5 decimal places like in original node-sass version.
